## Production of Machine Learning (Deserialization)

In [1]:
import numpy as np
import pickle 

In [2]:
# Loading pretrained classifiers from pickle files

model = pickle.load(open('models/Diabetes_final_lr.pkl', 'rb'))

scaler = pickle.load(open('models/StandardScaler.pkl','rb'))

In [3]:
# Reading the Query data

Pregnancies = int(input('Enter number of Pregnancies: '))
Glucose = int(input('Enter Glucose level: ' ))
BloodPressure = int(input('Enter Blood Pressure value: '))
SkinThickness = int(input('Enter Skin Thikness value: '))
Insulin = int(input('Enter Insulin level: '))
BMI = float(input('Enter BMI value: '))
DiabetesPedigreeFunction = float(input('Enter Diabetes Pedigree Function value: '))
Age = int(input('Enter Age of the Person: '))

'''prediction = model.predict(scaler.transform([[Pregnancies,Glucose,BloodPressure,SkinThickness, Insulin,BMI,DiabetesPedigreeFunction,Age]]))

if(prediction[0]==0):
    print('The person is not diabetic')
else:
    print('The person is diabetic') '''




Enter number of Pregnancies: 6
Enter Glucose level: 148
Enter Blood Pressure value: 72
Enter Skin Thikness value: 35
Enter Insulin level: 0
Enter BMI value: 33.6
Enter Diabetes Pedigree Function value: 0.627
Enter Age of the Person: 50


"prediction = model.predict(scaler.transform([[Pregnancies,Glucose,BloodPressure,SkinThickness, Insulin,BMI,DiabetesPedigreeFunction,Age]]))\n\nif(prediction[0]==0):\n    print('The person is not diabetic')\nelse:\n    print('The person is diabetic') "

### Converting the values to 2D array

In [4]:
query_point = np.array([Pregnancies,Glucose,BloodPressure,SkinThickness, Insulin,BMI,DiabetesPedigreeFunction,Age])

query_point

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ])

In [5]:
query_point.reshape(1,-1)

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ]])

In [6]:
query_point = query_point.reshape(1,-1)

query_point

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ]])

In [7]:
query_point_transformed = scaler.transform(query_point)

query_point_transformed

C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.63024068,  0.83361242,  0.08964217,  0.93754916, -0.80706674,
         0.21244641,  0.59741602,  1.42680431]])

In [8]:
prediction = model.predict(query_point_transformed)

if(prediction[0]==0):
    print('The person is not diabetic')
else:
    print('The person is diabetic')

The person is diabetic


### Production Ready Code

In [9]:
# Reading the Query data

Pregnancies = int(input('Enter number of Pregnancies: '))
Glucose = int(input('Enter Glucose level: ' ))
BloodPressure = int(input('Enter Blood Pressure value: '))
SkinThickness = int(input('Enter Skin Thikness value: '))
Insulin = int(input('Enter Insulin level: '))
BMI = float(input('Enter BMI value: '))
DiabetesPedigreeFunction = float(input('Enter Diabetes Pedigree Function value: '))
Age = int(input('Enter Age of the Person: '))

query_point = np.array([Pregnancies,Glucose,BloodPressure,SkinThickness, Insulin,BMI,DiabetesPedigreeFunction,Age]).reshape(1,-1)

query_point_transformed = scaler.transform(query_point)

prediction = model.predict(query_point_transformed)

if(prediction[0]==0):
    print('The person is not diabetic')
else:
    print('The person is diabetic')


Enter number of Pregnancies: 6
Enter Glucose level: 148
Enter Blood Pressure value: 72
Enter Skin Thikness value: 35
Enter Insulin level: 0
Enter BMI value: 33.6
Enter Diabetes Pedigree Function value: 0.627
Enter Age of the Person: 50
The person is diabetic


C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
